package com.zweicom.autoactivacionsim;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Estados implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private int etapa;
   private java.lang.Boolean etapa1;
   private java.lang.Boolean etapa2;
   private java.lang.Boolean etapa3;
   private java.lang.Boolean etapa4;
   private java.lang.Boolean etapa5;
   private java.lang.Boolean etapa6;
   private java.lang.Boolean etapa7;

   private int[] parte;

   public Estados()
   {
       this.parte = new int[7];
       for(int i=0; i <7 ;i++)
            parte[i] = 0;
       this.etapa1 = false;
       this.etapa2 = false;
       this.etapa3 = false;
       this.etapa4 = false;
       this.etapa5 = false;
       this.etapa6 = false;
       this.etapa7 = false;
   }
   
   public void siguienteEtapa(){
        this.etapa++;
        if(this.etapa == 1)
            this.etapa1 = true;
        else if(this.etapa == 2)
            this.etapa2 = true;
        else if(this.etapa == 3)
            this.etapa3 = true;
        else if(this.etapa == 4)
            this.etapa4 = true;
   }
   
   public void siguienteEtapa(int etapa){
        this.etapa++;
        if(etapa == 5)
            this.etapa5 = true;
        else if(etapa == 6)
            this.etapa6 = true;
        else if(etapa == 7)
            this.etapa7 = true;
   }

   public int getEtapa()
   {
      return this.etapa;
   }

   public void setEtapa(int etapa)
   {
      this.etapa = etapa;
   }

   public java.lang.Boolean getEtapa1()
   {
      return this.etapa1;
   }

   public void setEtapa1(java.lang.Boolean etapa1)
   {
      this.etapa1 = etapa1;
   }

   public java.lang.Boolean getEtapa2()
   {
      return this.etapa2;
   }

   public void setEtapa2(java.lang.Boolean etapa2)
   {
      this.etapa2 = etapa2;
   }

   public java.lang.Boolean getEtapa3()
   {
      return this.etapa3;
   }

   public void setEtapa3(java.lang.Boolean etapa3)
   {
      this.etapa3 = etapa3;
   }

   public java.lang.Boolean getEtapa4()
   {
      return this.etapa4;
   }

   public void setEtapa4(java.lang.Boolean etapa4)
   {
      this.etapa4 = etapa4;
   }

   public java.lang.Boolean getEtapa5()
   {
      return this.etapa5;
   }

   public void setEtapa5(java.lang.Boolean etapa5)
   {
      this.etapa5 = etapa5;
   }

   public java.lang.Boolean getEtapa6()
   {
      return this.etapa6;
   }

   public void setEtapa6(java.lang.Boolean etapa6)
   {
      this.etapa6 = etapa6;
   }

   public java.lang.Boolean getEtapa7()
   {
      return this.etapa7;
   }

   public void setEtapa7(java.lang.Boolean etapa7)
   {
      this.etapa7 = etapa7;
   }

   public int[] getParte()
   {
      return this.parte;
   }
   
   public int getParte(int etapa){
       return this.parte[etapa];
   }

   public void setParte(int[] parte)
   {
      this.parte = parte;
   }
   
   public void setParte(int etapa){
       this.parte[etapa]++;
   }

   public Estados(int etapa, java.lang.Boolean etapa1, java.lang.Boolean etapa2,
         java.lang.Boolean etapa3, java.lang.Boolean etapa4,
         java.lang.Boolean etapa5, java.lang.Boolean etapa6,
         java.lang.Boolean etapa7, int[] parte)
   {
      this.etapa = etapa;
      this.etapa1 = etapa1;
      this.etapa2 = etapa2;
      this.etapa3 = etapa3;
      this.etapa4 = etapa4;
      this.etapa5 = etapa5;
      this.etapa6 = etapa6;
      this.etapa7 = etapa7;
      this.parte = parte;
   }

}