package com.zweicom.autoactivacionsim;

/**
 * This class was automatically generated by the data modeler tool.
 */
import java.lang.Exception;

public class Parametros implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private int reintentosConsultarPersona = 6;

   private int reintentosCrearProspecto = 6;

   private int reintentosActualizarClienteReneic = 6;

   private int tiempoCrearProspecto = 10;

   private int tiempoActualizarClienteReniec = 10;

   private int tiempoConsultarPersona = 10;

   private int reintentosRegistrarCambioPlan = 6;

   private int tiempoRegistrarCambioPlan = 10;

   private int reintentosValidarProcesoPendiente = 6;

   private int tiempoValidarProcesoPendiente = 10;

   private int reintentosCambiarEstadoServicio = 6;

   private int tiempoCambiarEstadoServicio = 10;

   private int reintentosModificarCuenta = 6;

   private int tiempoModificarCuenta = 10;

   private int reintentosObtenerPlan = 6;

   private int tiempoObtenerPlan = 10;

   private int reintentosObtenerLineasCliente = 6;

   private int tiempoObtenerLineasCliente = 10;

   private int reintentosFormatearTelefono = 6;

   private int tiempoFormatearTelefono = 10;

   private int reintentosCrearOrdenPorCliente = 6;

   private int tiempoCrearOrdenPorCliente = 10;

   private int reintentosConsultarDatosClienteVista2 = 6;

   private int tiempoConsultarDatosClienteVista2 = 10;

   private int reintentosCrearClienteBSCS = 6;

   private int tiempoCrearClienteBSCS = 10;

   private int reintentosSincronizarClienteBSCS = 6;

   private int tiempoSincronizarClienteBSCS = 10;

   private int reintentosConsultarDatosReniec = 6;

   private int tiempoConsultarDatosReniec = 10;

   private int reintentosCambiarTitularContrato = 6;

   private int tiempoCambiarTitularContrato = 10;

   private int reintentosGenericos = 6;

   private int tiempoGenericos = 10;

   private int reintentosObtenerEstadoProceso = 6;

   private int tiempoObtenerEstadoProceso = 10;

   public Parametros()
   {
   }

   public int getReintentosConsultarPersona()
   {
      return this.reintentosConsultarPersona;
   }

   public void setReintentosConsultarPersona(int reintentosConsultarPersona)
   {
      this.reintentosConsultarPersona = reintentosConsultarPersona;
   }

   public int getReintentosCrearProspecto()
   {
      return this.reintentosCrearProspecto;
   }

   public void setReintentosCrearProspecto(int reintentosCrearProspecto)
   {
      this.reintentosCrearProspecto = reintentosCrearProspecto;
   }

   public int getReintentosActualizarClienteReneic()
   {
      return this.reintentosActualizarClienteReneic;
   }

   public void setReintentosActualizarClienteReneic(
         int reintentosActualizarClienteReneic)
   {
      this.reintentosActualizarClienteReneic = reintentosActualizarClienteReneic;
   }

   public int getTiempoCrearProspecto()
   {
      return this.tiempoCrearProspecto;
   }

   public void setTiempoCrearProspecto(int tiempoCrearProspecto)
   {
      this.tiempoCrearProspecto = tiempoCrearProspecto;
   }

   public int getTiempoActualizarClienteReniec()
   {
      return this.tiempoActualizarClienteReniec;
   }

   public void setTiempoActualizarClienteReniec(int tiempoActualizarClienteReniec)
   {
      this.tiempoActualizarClienteReniec = tiempoActualizarClienteReniec;
   }

   public int getTiempoConsultarPersona()
   {
      return this.tiempoConsultarPersona;
   }

   public void setTiempoConsultarPersona(int tiempoConsultarPersona)
   {
      this.tiempoConsultarPersona = tiempoConsultarPersona;
   }

   public int getReintentosRegistrarCambioPlan()
   {
      return this.reintentosRegistrarCambioPlan;
   }

   public void setReintentosRegistrarCambioPlan(int reintentosRegistrarCambioPlan)
   {
      this.reintentosRegistrarCambioPlan = reintentosRegistrarCambioPlan;
   }

   public int getTiempoRegistrarCambioPlan()
   {
      return this.tiempoRegistrarCambioPlan;
   }

   public void setTiempoRegistrarCambioPlan(int tiempoRegistrarCambioPlan)
   {
      this.tiempoRegistrarCambioPlan = tiempoRegistrarCambioPlan;
   }

   public int getReintentosValidarProcesoPendiente()
   {
      return this.reintentosValidarProcesoPendiente;
   }

   public void setReintentosValidarProcesoPendiente(
         int reintentosValidarProcesoPendiente)
   {
      this.reintentosValidarProcesoPendiente = reintentosValidarProcesoPendiente;
   }

   public int getTiempoValidarProcesoPendiente()
   {
      return this.tiempoValidarProcesoPendiente;
   }

   public void setTiempoValidarProcesoPendiente(int tiempoValidarProcesoPendiente)
   {
      this.tiempoValidarProcesoPendiente = tiempoValidarProcesoPendiente;
   }

   public int getReintentosCambiarEstadoServicio()
   {
      return this.reintentosCambiarEstadoServicio;
   }

   public void setReintentosCambiarEstadoServicio(
         int reintentosCambiarEstadoServicio)
   {
      this.reintentosCambiarEstadoServicio = reintentosCambiarEstadoServicio;
   }

   public int getTiempoCambiarEstadoServicio()
   {
      return this.tiempoCambiarEstadoServicio;
   }

   public void setTiempoCambiarEstadoServicio(int tiempoCambiarEstadoServicio)
   {
      this.tiempoCambiarEstadoServicio = tiempoCambiarEstadoServicio;
   }

   public int getReintentosModificarCuenta()
   {
      return this.reintentosModificarCuenta;
   }

   public void setReintentosModificarCuenta(int reintentosModificarCuenta)
   {
      this.reintentosModificarCuenta = reintentosModificarCuenta;
   }

   public int getTiempoModificarCuenta()
   {
      return this.tiempoModificarCuenta;
   }

   public void setTiempoModificarCuenta(int tiempoModificarCuenta)
   {
      this.tiempoModificarCuenta = tiempoModificarCuenta;
   }

   public int getReintentosObtenerPlan()
   {
      return this.reintentosObtenerPlan;
   }

   public void setReintentosObtenerPlan(int reintentosObtenerPlan)
   {
      this.reintentosObtenerPlan = reintentosObtenerPlan;
   }

   public int getTiempoObtenerPlan()
   {
      return this.tiempoObtenerPlan;
   }

   public void setTiempoObtenerPlan(int tiempoObtenerPlan)
   {
      this.tiempoObtenerPlan = tiempoObtenerPlan;
   }

   public int getReintentosObtenerLineasCliente()
   {
      return this.reintentosObtenerLineasCliente;
   }

   public void setReintentosObtenerLineasCliente(int reintentosObtenerLineasCliente)
   {
      this.reintentosObtenerLineasCliente = reintentosObtenerLineasCliente;
   }

   public int getTiempoObtenerLineasCliente()
   {
      return this.tiempoObtenerLineasCliente;
   }

   public void setTiempoObtenerLineasCliente(int tiempoObtenerLineasCliente)
   {
      this.tiempoObtenerLineasCliente = tiempoObtenerLineasCliente;
   }

   public int getReintentosFormatearTelefono()
   {
      return this.reintentosFormatearTelefono;
   }

   public void setReintentosFormatearTelefono(int reintentosFormatearTelefono)
   {
      this.reintentosFormatearTelefono = reintentosFormatearTelefono;
   }

   public int getTiempoFormatearTelefono()
   {
      return this.tiempoFormatearTelefono;
   }

   public void setTiempoFormatearTelefono(int tiempoFormatearTelefono)
   {
      this.tiempoFormatearTelefono = tiempoFormatearTelefono;
   }

   public int getReintentosCrearOrdenPorCliente()
   {
      return this.reintentosCrearOrdenPorCliente;
   }

   public void setReintentosCrearOrdenPorCliente(int reintentosCrearOrdenPorCliente)
   {
      this.reintentosCrearOrdenPorCliente = reintentosCrearOrdenPorCliente;
   }

   public int getTiempoCrearOrdenPorCliente()
   {
      return this.tiempoCrearOrdenPorCliente;
   }

   public void setTiempoCrearOrdenPorCliente(int tiempoCrearOrdenPorCliente)
   {
      this.tiempoCrearOrdenPorCliente = tiempoCrearOrdenPorCliente;
   }

   public int getReintentosConsultarDatosClienteVista2()
   {
      return this.reintentosConsultarDatosClienteVista2;
   }

   public void setReintentosConsultarDatosClienteVista2(
         int reintentosConsultarDatosClienteVista2)
   {
      this.reintentosConsultarDatosClienteVista2 = reintentosConsultarDatosClienteVista2;
   }

   public int getTiempoConsultarDatosClienteVista2()
   {
      return this.tiempoConsultarDatosClienteVista2;
   }

   public void setTiempoConsultarDatosClienteVista2(
         int tiempoConsultarDatosClienteVista2)
   {
      this.tiempoConsultarDatosClienteVista2 = tiempoConsultarDatosClienteVista2;
   }

   public int getReintentosCrearClienteBSCS()
   {
      return this.reintentosCrearClienteBSCS;
   }

   public void setReintentosCrearClienteBSCS(int reintentosCrearClienteBSCS)
   {
      this.reintentosCrearClienteBSCS = reintentosCrearClienteBSCS;
   }

   public int getTiempoCrearClienteBSCS()
   {
      return this.tiempoCrearClienteBSCS;
   }

   public void setTiempoCrearClienteBSCS(int tiempoCrearClienteBSCS)
   {
      this.tiempoCrearClienteBSCS = tiempoCrearClienteBSCS;
   }

   public int getReintentosSincronizarClienteBSCS()
   {
      return this.reintentosSincronizarClienteBSCS;
   }

   public void setReintentosSincronizarClienteBSCS(
         int reintentosSincronizarClienteBSCS)
   {
      this.reintentosSincronizarClienteBSCS = reintentosSincronizarClienteBSCS;
   }

   public int getTiempoSincronizarClienteBSCS()
   {
      return this.tiempoSincronizarClienteBSCS;
   }

   public void setTiempoSincronizarClienteBSCS(int tiempoSincronizarClienteBSCS)
   {
      this.tiempoSincronizarClienteBSCS = tiempoSincronizarClienteBSCS;
   }

   public int getReintentosConsultarDatosReniec()
   {
      return this.reintentosConsultarDatosReniec;
   }

   public void setReintentosConsultarDatosReniec(int reintentosConsultarDatosReniec)
   {
      this.reintentosConsultarDatosReniec = reintentosConsultarDatosReniec;
   }

   public int getTiempoConsultarDatosReniec()
   {
      return this.tiempoConsultarDatosReniec;
   }

   public void setTiempoConsultarDatosReniec(int tiempoConsultarDatosReniec)
   {
      this.tiempoConsultarDatosReniec = tiempoConsultarDatosReniec;
   }

   public int getReintentosCambiarTitularContrato()
   {
      return this.reintentosCambiarTitularContrato;
   }

   public void setReintentosCambiarTitularContrato(
         int reintentosCambiarTitularContrato)
   {
      this.reintentosCambiarTitularContrato = reintentosCambiarTitularContrato;
   }

   public int getTiempoCambiarTitularContrato()
   {
      return this.tiempoCambiarTitularContrato;
   }

   public void setTiempoCambiarTitularContrato(int tiempoCambiarTitularContrato)
   {
      this.tiempoCambiarTitularContrato = tiempoCambiarTitularContrato;
   }

   public int getReintentosGenericos()
   {
      return this.reintentosGenericos;
   }

   public void setReintentosGenericos(int reintentosGenericos)
   {
      this.reintentosGenericos = reintentosGenericos;
   }

   public int getTiempoGenericos()
   {
      return this.tiempoGenericos;
   }

   public void setTiempoGenericos(int tiempoGenericos)
   {
      this.tiempoGenericos = tiempoGenericos;
   }

   public int getReintentosObtenerEstadoProceso()
   {
      return this.reintentosObtenerEstadoProceso;
   }

   public void setReintentosObtenerEstadoProceso(int reintentosObtenerEstadoProceso)
   {
      this.reintentosObtenerEstadoProceso = reintentosObtenerEstadoProceso;
   }

   public int getTiempoObtenerEstadoProceso()
   {
      return this.tiempoObtenerEstadoProceso;
   }

   public void setTiempoObtenerEstadoProceso(int tiempoObtenerEstadoProceso)
   {
      this.tiempoObtenerEstadoProceso = tiempoObtenerEstadoProceso;
   }

   public Parametros(int reintentosConsultarPersona, int reintentosCrearProspecto,
         int reintentosActualizarClienteReneic, int tiempoCrearProspecto,
         int tiempoActualizarClienteReniec, int tiempoConsultarPersona,
         int reintentosRegistrarCambioPlan, int tiempoRegistrarCambioPlan,
         int reintentosValidarProcesoPendiente,
         int tiempoValidarProcesoPendiente, int reintentosCambiarEstadoServicio,
         int tiempoCambiarEstadoServicio, int reintentosModificarCuenta,
         int tiempoModificarCuenta, int reintentosObtenerPlan,
         int tiempoObtenerPlan, int reintentosObtenerLineasCliente,
         int tiempoObtenerLineasCliente, int reintentosFormatearTelefono,
         int tiempoFormatearTelefono, int reintentosCrearOrdenPorCliente,
         int tiempoCrearOrdenPorCliente,
         int reintentosConsultarDatosClienteVista2,
         int tiempoConsultarDatosClienteVista2, int reintentosCrearClienteBSCS,
         int tiempoCrearClienteBSCS, int reintentosSincronizarClienteBSCS,
         int tiempoSincronizarClienteBSCS, int reintentosConsultarDatosReniec,
         int tiempoConsultarDatosReniec, int reintentosCambiarTitularContrato,
         int tiempoCambiarTitularContrato, int reintentosGenericos,
         int tiempoGenericos, int reintentosObtenerEstadoProceso,
         int tiempoObtenerEstadoProceso)
   {
      this.reintentosConsultarPersona = reintentosConsultarPersona;
      this.reintentosCrearProspecto = reintentosCrearProspecto;
      this.reintentosActualizarClienteReneic = reintentosActualizarClienteReneic;
      this.tiempoCrearProspecto = tiempoCrearProspecto;
      this.tiempoActualizarClienteReniec = tiempoActualizarClienteReniec;
      this.tiempoConsultarPersona = tiempoConsultarPersona;
      this.reintentosRegistrarCambioPlan = reintentosRegistrarCambioPlan;
      this.tiempoRegistrarCambioPlan = tiempoRegistrarCambioPlan;
      this.reintentosValidarProcesoPendiente = reintentosValidarProcesoPendiente;
      this.tiempoValidarProcesoPendiente = tiempoValidarProcesoPendiente;
      this.reintentosCambiarEstadoServicio = reintentosCambiarEstadoServicio;
      this.tiempoCambiarEstadoServicio = tiempoCambiarEstadoServicio;
      this.reintentosModificarCuenta = reintentosModificarCuenta;
      this.tiempoModificarCuenta = tiempoModificarCuenta;
      this.reintentosObtenerPlan = reintentosObtenerPlan;
      this.tiempoObtenerPlan = tiempoObtenerPlan;
      this.reintentosObtenerLineasCliente = reintentosObtenerLineasCliente;
      this.tiempoObtenerLineasCliente = tiempoObtenerLineasCliente;
      this.reintentosFormatearTelefono = reintentosFormatearTelefono;
      this.tiempoFormatearTelefono = tiempoFormatearTelefono;
      this.reintentosCrearOrdenPorCliente = reintentosCrearOrdenPorCliente;
      this.tiempoCrearOrdenPorCliente = tiempoCrearOrdenPorCliente;
      this.reintentosConsultarDatosClienteVista2 = reintentosConsultarDatosClienteVista2;
      this.tiempoConsultarDatosClienteVista2 = tiempoConsultarDatosClienteVista2;
      this.reintentosCrearClienteBSCS = reintentosCrearClienteBSCS;
      this.tiempoCrearClienteBSCS = tiempoCrearClienteBSCS;
      this.reintentosSincronizarClienteBSCS = reintentosSincronizarClienteBSCS;
      this.tiempoSincronizarClienteBSCS = tiempoSincronizarClienteBSCS;
      this.reintentosConsultarDatosReniec = reintentosConsultarDatosReniec;
      this.tiempoConsultarDatosReniec = tiempoConsultarDatosReniec;
      this.reintentosCambiarTitularContrato = reintentosCambiarTitularContrato;
      this.tiempoCambiarTitularContrato = tiempoCambiarTitularContrato;
      this.reintentosGenericos = reintentosGenericos;
      this.tiempoGenericos = tiempoGenericos;
      this.reintentosObtenerEstadoProceso = reintentosObtenerEstadoProceso;
      this.tiempoObtenerEstadoProceso = tiempoObtenerEstadoProceso;
   }

}