package com.zweicom.autoactivacionsim;

import java.util.Map;
/**
 * This class was automatically generated by the data modeler tool.
 */

public class PersonaReniec implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String numeroDocumento;
   private java.lang.String tipoDocumento;
   private java.lang.String nombres;
   private java.lang.String primerApellido;
   private java.lang.String segundoApellido;
   private java.lang.String genero;
   private java.util.Date fechaNacimiento;
   private Map direccionReniec;

   public PersonaReniec()
   {
   }

   public java.lang.String getNumeroDocumento()
   {
      return this.numeroDocumento;
   }

   public void setNumeroDocumento(java.lang.String numeroDocumento)
   {
      this.numeroDocumento = numeroDocumento;
   }

   public java.lang.String getTipoDocumento()
   {
      return this.tipoDocumento;
   }

   public void setTipoDocumento(java.lang.String tipoDocumento)
   {
      this.tipoDocumento = tipoDocumento;
   }

   public java.lang.String getNombres()
   {
      return this.nombres;
   }

   public void setNombres(java.lang.String nombres)
   {
      this.nombres = nombres;
   }

   public java.lang.String getPrimerApellido()
   {
      return this.primerApellido;
   }

   public void setPrimerApellido(java.lang.String primerApellido)
   {
      this.primerApellido = primerApellido;
   }

   public java.lang.String getSegundoApellido()
   {
      return this.segundoApellido;
   }

   public void setSegundoApellido(java.lang.String segundoApellido)
   {
      this.segundoApellido = segundoApellido;
   }

   public java.lang.String getGenero()
   {
      return this.genero;
   }

   public void setGenero(java.lang.String genero)
   {
      this.genero = genero;
   }

   public java.util.Date getFechaNacimiento()
   {
      return this.fechaNacimiento;
   }

   public void setFechaNacimiento(java.util.Date fechaNacimiento)
   {
      this.fechaNacimiento = fechaNacimiento;
   }

   public PersonaReniec(java.lang.String numeroDocumento,
         java.lang.String tipoDocumento, java.lang.String nombres,
         java.lang.String primerApellido, java.lang.String segundoApellido,
         java.lang.String genero, java.util.Date fechaNacimiento)
   {
      this.numeroDocumento = numeroDocumento;
      this.tipoDocumento = tipoDocumento;
      this.nombres = nombres;
      this.primerApellido = primerApellido;
      this.segundoApellido = segundoApellido;
      this.genero = genero;
      this.fechaNacimiento = fechaNacimiento;
   }

}