package com.zweicom.autoactivacionsim;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TimeoutException implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public TimeoutException() {
    }

}